### ISSUE TITLE
putItem always respond with None

### ISSUE THREAD

**Issue by stanislav-chetvertkov** [zio/zio-dynamodb#399]
It seems that when inserting an new time the call it always yields an empty result

```
DynamoDBQuery.putItem(tableName, attributes)
```
where
```
def putItem(tableName: String, item: Item): DynamoDBQuery[Any, Option[Item]] = PutItem(TableName(tableName), item)
....

  private[dynamodb] final case class PutItem(
    tableName: TableName,
    item: Item,
    conditionExpression: Option[ConditionExpression[_]] = None,
    capacity: ReturnConsumedCapacity = ReturnConsumedCapacity.None,
    itemMetrics: ReturnItemCollectionMetrics = ReturnItemCollectionMetrics.None,
    returnValues: ReturnValues = ReturnValues.None // PutItem does not recognize any values other than NONE or ALL_OLD.
  ) extends Write[Any, Option[Item]]
```

It seems to have something to do with ` returnValues: ReturnValues = ReturnValues.None` and I couldn't find a way to override it, is this accurate and is there a way to override it so that the inserted record is returned in the result?

**Comment by googley42** [comment]
@stanislav-chetvertkov many thanks for your feedback. ATM there is no way of specifying this value. The valid values `returnValues` for a PutItem request are `NONE` and `ALL_OLD` - is your requirement to be able to conditionally specify ALL_OLD values? Is this a requirement you currently have?

I should be able to start looking at this next week.

**Comment by stanislav-chetvertkov** [comment]
If my understanding is correct then calling `putItem` should yield nothing (None) if the item hasn't been written
for example, if I have a conditional expression for optimistic locking
```
DynamoDBQuery.putItem(tableName, attrs)
          .where($("version") === currentVersion)
```
if the condition matched I expect the value to be written and `Some(attrs)` be returned or otherwise it should be `None`
Though maybe I misunderstood the way it should behave...

**Comment by googley42** [comment]
so that's not how `putItem` or the underlying AWS `PutItem` work - for `PutItem` you have to specify the [`ReturnValues`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#DDB-PutItem-request-ReturnValues) in the request - which can be `NONE` (default) or `ALL_OLD`  - in the 2nd case it will return old values if these existed before the PutItem.

So I could have a look at doing something like changing the `putItem` signature so that you can specify via an extra parameter that you want the old values

**Comment by stanislav-chetvertkov** [comment]
Thanks for clarifying!
I guess the ability to override certain arguments for the case classes in DynamoDBQuery where it makes sense would be useful in general

**Comment by googley42** [comment]
@stanislav-chetvertkov even better - we already have this facility for `updateItem` - apologies I totally forgot - [see this integration test](https://github.com/zio/zio-dynamodb/blob/series/2.x/dynamodb/src/it/scala/zio/dynamodb/LiveSpec.scala#L871-L873)
- its via the `returns` method

```scala
                updatedResponse <- updateItem(tableName, pk(adamItem))($(name).set(notAdam))
                                     .returns(ReturnValues.AllOld)
                                     .execute
```

so the fix for `putItem` would take the approach

**Comment by stanislav-chetvertkov** [comment]
ah, yes I didn't notice that, thanks!

**Comment by googley42** [comment]
ah I think you may need to keep this issue open as I think although the syntax exists for `putItem`, I think a fix is needed to make it actually work

**Comment by googley42** [comment]
@stanislav-chetvertkov I think I have fixed the issue. There is an IT example [here](https://github.com/zio/zio-dynamodb/blob/series/2.x/dynamodb/src/it/scala/zio/dynamodb/LiveSpec.scala#L500-L516) - could you try the latest snapshot version `1.0.0-RC2+8-822c5778-SNAPSHOT` please to confirm that this works. You will need to add the line `resolvers += Resolver.sonatypeRepo("snapshots")` to your buid.sbt

**Comment by stanislav-chetvertkov** [comment]
the fix in https://github.com/zio/zio-dynamodb/pull/402/files looks good
